INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00001','Pulsa Axis paket SMS puas','Rp7000','Pulsa Axis paket SMS puas bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00002','Pulsa Axis','Rp12000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00003','Pulsa IM3 kuota 3 GB malam','Rp27000','Pulsa IM3 kuota 3 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00004','Pulsa IM3 kuota 1 GB malam','Rp52000','Pulsa IM3 kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00005','Pulsa Bolt','Rp102000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00006','Pulsa Telkomsel kuota unlimited','Rp152000','Pulsa Telkomsel kuota unlimited');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00007','Pulsa IM3','Rp202000','Pulsa IM3  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00008','Pulsa Bolt','Rp7000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P00009','Pulsa Mentari','Rp12000','Pulsa Mentari  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000010','Pulsa Three paket SMS sesama','Rp27000','Pulsa Three paket SMS sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000011','Pulsa Bolt','Rp52000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000012','Pulsa Mentari','Rp102000','Pulsa Mentari  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000013','Pulsa Simpati','Rp152000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000014','Pulsa Mentari','Rp202000','Pulsa Mentari  bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000015','Pulsa Simpati kuota 3 GB','Rp7000','Pulsa Simpati kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000016','Pulsa Bolt','Rp12000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000017','Pulsa Axis','Rp27000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000018','Pulsa Telkomsel','Rp52000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000019','Pulsa Simpati','Rp102000','Pulsa Simpati  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000020','Pulsa Bolt paket WiFi','Rp152000','Pulsa Bolt paket WiFi');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000021','Pulsa Telkomsel paket WiFi','Rp202000','Pulsa Telkomsel paket WiFi');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000022','Pulsa Axis kuota 2 GB','Rp7000','Pulsa Axis kuota 2 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000023','Pulsa Simpati kuota 1 GB malam','Rp12000','Pulsa Simpati kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000024','Pulsa Smart Fren paket nelpon puas','Rp27000','Pulsa Smart Fren paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000025','Pulsa Telkomsel','Rp52000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000026','Pulsa Simpati','Rp102000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000027','Pulsa Simpati kuota 1 GB malam','Rp152000','Pulsa Simpati kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000028','Pulsa Axis kuota 2 GB','Rp202000','Pulsa Axis kuota 2 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000029','Pulsa Telkomsel kuota 2 GB','Rp7000','Pulsa Telkomsel kuota 2 GB bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000030','Pulsa Mentari','Rp12000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000031','Pulsa Mentari kuota unlimited','Rp27000','Pulsa Mentari kuota unlimited bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000032','Pulsa Simpati','Rp52000','Pulsa Simpati  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000033','Pulsa Bolt','Rp102000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000034','Pulsa IM3 paket nelpon puas','Rp152000','Pulsa IM3 paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000035','Pulsa Axis','Rp202000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000036','Pulsa Bolt kuota unlimited','Rp7000','Pulsa Bolt kuota unlimited');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000037','Pulsa Mentari kuota 3 GB malam','Rp12000','Pulsa Mentari kuota 3 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000038','Pulsa Mentari kuota 3 GB','Rp27000','Pulsa Mentari kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000039','Pulsa Bolt','Rp52000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000040','Pulsa Mentari paket WiFi','Rp102000','Pulsa Mentari paket WiFi');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000041','Pulsa Axis kuota 3 GB','Rp152000','Pulsa Axis kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000042','Pulsa Simpati','Rp202000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000043','Pulsa Smart Fren kuota 2 GB','Rp7000','Pulsa Smart Fren kuota 2 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000044','Pulsa Telkomsel kuota 3 GB','Rp12000','Pulsa Telkomsel kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000045','Pulsa Mentari','Rp27000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000046','Pulsa Three','Rp52000','Pulsa Three');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000047','Pulsa Axis paket nelpon puas','Rp102000','Pulsa Axis paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000048','Pulsa Bolt','Rp152000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000049','Pulsa Axis','Rp202000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000050','Pulsa Bolt','Rp7000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000051','Pulsa Smart Fren kuota 12 GB malam','Rp12000','Pulsa Smart Fren kuota 12 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000052','Pulsa Smart Fren kuota 3 GB','Rp27000','Pulsa Smart Fren kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000053','Pulsa Axis kuota 1 GB','Rp52000','Pulsa Axis kuota 1 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000054','Pulsa Axis paket nelpon sesama','Rp102000','Pulsa Axis paket nelpon sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000055','Pulsa Simpati kuota unlimited','Rp152000','Pulsa Simpati kuota unlimited bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000056','Pulsa Mentari','Rp202000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000057','Pulsa Bolt','Rp7000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000058','Pulsa Axis','Rp12000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000059','Pulsa Simpati','Rp27000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000060','Pulsa Telkomsel','Rp52000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000061','Pulsa Smart Fren','Rp102000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000062','Pulsa Smart Fren kuota 1 GB malam','Rp152000','Pulsa Smart Fren kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000063','Pulsa Smart Fren','Rp202000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000064','Pulsa Simpati kuota 12 GB malam','Rp7000','Pulsa Simpati kuota 12 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000065','Pulsa IM3','Rp12000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000066','Pulsa IM3 kuota 3 GB malam','Rp27000','Pulsa IM3 kuota 3 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000067','Pulsa Telkomsel','Rp52000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000068','Pulsa IM3','Rp102000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000069','Pulsa Three','Rp152000','Pulsa Three  bonus kuota 4 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000070','Pulsa Axis kuota 1 GB malam','Rp202000','Pulsa Axis kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000071','Pulsa Three kuota 12 GB malam','Rp7000','Pulsa Three kuota 12 GB malam bonus kuota 4 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000072','Pulsa Mentari','Rp12000','Pulsa Mentari  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000073','Pulsa Smart Fren kuota 12 GB malam','Rp27000','Pulsa Smart Fren kuota 12 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000074','Pulsa Simpati','Rp52000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000075','Pulsa Smart Fren kuota unlimited','Rp102000','Pulsa Smart Fren kuota unlimited');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000076','Pulsa Three','Rp152000','Pulsa Three');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000077','Pulsa Bolt paket nelpon puas','Rp202000','Pulsa Bolt paket nelpon puas bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000078','Pulsa Smart Fren','Rp7000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000079','Pulsa Telkomsel paket SMS sesama','Rp12000','Pulsa Telkomsel paket SMS sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000080','Pulsa Axis paket SMS puas','Rp27000','Pulsa Axis paket SMS puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000081','Pulsa Axis kuota 1 GB malam','Rp52000','Pulsa Axis kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000082','Pulsa Mentari','Rp102000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000083','Pulsa Mentari','Rp152000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000084','Pulsa Axis','Rp202000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000085','Pulsa Telkomsel','Rp7000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000086','Pulsa Smart Fren kuota unlimited','Rp12000','Pulsa Smart Fren kuota unlimited');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000087','Pulsa Smart Fren','Rp27000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000088','Pulsa Mentari','Rp52000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000089','Pulsa Mentari kuota 3 GB malam','Rp102000','Pulsa Mentari kuota 3 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000090','Pulsa IM3','Rp152000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000091','Pulsa Simpati paket nelpon puas','Rp202000','Pulsa Simpati paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000092','Pulsa Smart Fren kuota 2 GB','Rp7000','Pulsa Smart Fren kuota 2 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000093','Pulsa Simpati kuota 1 GB','Rp12000','Pulsa Simpati kuota 1 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000094','Pulsa Simpati kuota 1 GB','Rp27000','Pulsa Simpati kuota 1 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000095','Pulsa Mentari','Rp52000','Pulsa Mentari  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000096','Pulsa Three paket SMS sesama','Rp102000','Pulsa Three paket SMS sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000097','Pulsa Simpati','Rp152000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000098','Pulsa Three paket SMS puas','Rp202000','Pulsa Three paket SMS puas bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P000099','Pulsa IM3','Rp7000','Pulsa IM3  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000100','Pulsa Bolt','Rp12000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000101','Pulsa Smart Fren kuota unlimited','Rp27000','Pulsa Smart Fren kuota unlimited');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000102','Pulsa Smart Fren','Rp52000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000103','Pulsa Simpati','Rp102000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000104','Pulsa Telkomsel','Rp152000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000105','Pulsa IM3','Rp202000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000106','Pulsa Simpati','Rp7000','Pulsa Simpati  bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000107','Pulsa Mentari','Rp12000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000108','Pulsa Bolt','Rp27000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000109','Pulsa Axis kuota 1 GB malam','Rp52000','Pulsa Axis kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000110','Pulsa Axis','Rp102000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000111','Pulsa Mentari kuota 1 GB','Rp152000','Pulsa Mentari kuota 1 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000112','Pulsa IM3','Rp202000','Pulsa IM3  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000113','Pulsa Telkomsel kuota 1 GB malam','Rp7000','Pulsa Telkomsel kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000114','Pulsa Telkomsel','Rp12000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000115','Pulsa Simpati kuota 5 GB','Rp27000','Pulsa Simpati kuota 5 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000116','Pulsa Simpati','Rp52000','Pulsa Simpati  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000117','Pulsa Simpati','Rp102000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000118','Pulsa Smart Fren','Rp152000','Pulsa Smart Fren  bonus kuota 4 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000119','Pulsa Bolt','Rp202000','Pulsa Bolt  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000120','Pulsa Bolt paket nelpon sesama','Rp7000','Pulsa Bolt paket nelpon sesama bonus kuota 4 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000121','Pulsa Simpati','Rp12000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000122','Pulsa Mentari kuota 1 GB','Rp27000','Pulsa Mentari kuota 1 GB bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000123','Pulsa IM3','Rp52000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000124','Pulsa Telkomsel kuota 1 GB malam','Rp102000','Pulsa Telkomsel kuota 1 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000125','Pulsa Mentari','Rp152000','Pulsa Mentari  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000126','Pulsa Simpati','Rp202000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000127','Pulsa Telkomsel','Rp7000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000128','Pulsa IM3','Rp12000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000129','Pulsa Axis','Rp27000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000130','Pulsa Bolt paket WiFi','Rp52000','Pulsa Bolt paket WiFi');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000131','Pulsa Bolt','Rp102000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000132','Pulsa Telkomsel','Rp152000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000133','Pulsa Axis','Rp202000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000134','Pulsa Bolt paket nelpon sesama','Rp7000','Pulsa Bolt paket nelpon sesama bonus kuota 4 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000135','Pulsa Three','Rp12000','Pulsa Three');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000136','Pulsa Simpati','Rp27000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000137','Pulsa IM3','Rp52000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000138','Pulsa Bolt','Rp102000','Pulsa Bolt  bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000139','Pulsa Bolt','Rp152000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000140','Pulsa Simpati','Rp202000','Pulsa Simpati  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000141','Pulsa Mentari','Rp7000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000142','Pulsa Three','Rp12000','Pulsa Three');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000143','Pulsa Axis','Rp27000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000144','Pulsa Three','Rp52000','Pulsa Three  bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000145','Pulsa Simpati','Rp102000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000146','Pulsa Smart Fren','Rp152000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000147','Pulsa Simpati paket nelpon puas','Rp202000','Pulsa Simpati paket nelpon puas bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000148','Pulsa Smart Fren paket nelpon puas','Rp7000','Pulsa Smart Fren paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000149','Pulsa IM3 kuota 5 GB','Rp12000','Pulsa IM3 kuota 5 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000150','Pulsa Smart Fren','Rp27000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000151','Pulsa Three kuota 12 GB malam','Rp52000','Pulsa Three kuota 12 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000152','Pulsa Three kuota 5 GB','Rp102000','Pulsa Three kuota 5 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000153','Pulsa Bolt kuota 5 GB','Rp152000','Pulsa Bolt kuota 5 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000154','Pulsa Axis kuota 2 GB','Rp202000','Pulsa Axis kuota 2 GB bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000155','Pulsa Simpati','Rp7000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000156','Pulsa Mentari','Rp12000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000157','Pulsa Axis paket SMS puas','Rp27000','Pulsa Axis paket SMS puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000158','Pulsa Mentari paket nelpon sesama','Rp52000','Pulsa Mentari paket nelpon sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000159','Pulsa Bolt','Rp102000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000160','Pulsa Mentari paket SMS sesama','Rp152000','Pulsa Mentari paket SMS sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000161','Pulsa Bolt','Rp202000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000162','Pulsa Simpati','Rp7000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000163','Pulsa Axis','Rp12000','Pulsa Axis  bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000164','Pulsa IM3','Rp27000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000165','Pulsa Axis','Rp52000','Pulsa Axis  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000166','Pulsa Bolt','Rp102000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000167','Pulsa Smart Fren kuota 3 GB malam','Rp152000','Pulsa Smart Fren kuota 3 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000168','Pulsa Bolt kuota 1 GB malam','Rp202000','Pulsa Bolt kuota 1 GB malam bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000169','Pulsa Telkomsel kuota 5 GB','Rp7000','Pulsa Telkomsel kuota 5 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000170','Pulsa Mentari paket SMS puas','Rp12000','Pulsa Mentari paket SMS puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000171','Pulsa IM3 kuota 12 GB malam','Rp27000','Pulsa IM3 kuota 12 GB malam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000172','Pulsa Telkomsel kuota 1 GB','Rp52000','Pulsa Telkomsel kuota 1 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000173','Pulsa Mentari','Rp102000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000174','Pulsa Axis','Rp152000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000175','Pulsa Telkomsel','Rp202000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000176','Pulsa Bolt','Rp7000','Pulsa Bolt  bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000177','Pulsa Bolt paket SMS puas','Rp12000','Pulsa Bolt paket SMS puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000178','Pulsa Axis paket nelpon puas','Rp27000','Pulsa Axis paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000179','Pulsa Axis','Rp52000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000180','Pulsa Axis','Rp102000','Pulsa Axis');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000181','Pulsa Mentari kuota 2 GB','Rp152000','Pulsa Mentari kuota 2 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000182','Pulsa Simpati','Rp202000','Pulsa Simpati  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000183','Pulsa Mentari','Rp7000','Pulsa Mentari  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000184','Pulsa Bolt','Rp12000','Pulsa Bolt');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000185','Pulsa Simpati','Rp27000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000186','Pulsa Simpati','Rp52000','Pulsa Simpati');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000187','Pulsa Telkomsel kuota 3 GB','Rp102000','Pulsa Telkomsel kuota 3 GB bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000188','Pulsa IM3','Rp152000','Pulsa IM3');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000189','Pulsa Three kuota unlimited','Rp202000','Pulsa Three kuota unlimited bonus kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000190','Pulsa Mentari','Rp7000','Pulsa Mentari');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000191','Pulsa Simpati paket nelpon puas','Rp12000','Pulsa Simpati paket nelpon puas bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000192','Pulsa IM3 kuota 1 GB malam','Rp27000','Pulsa IM3 kuota 1 GB malam bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000193','Pulsa Three paket nelpon puas','Rp52000','Pulsa Three paket nelpon puas');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000194','Pulsa IM3 kuota 3 GB','Rp102000','Pulsa IM3 kuota 3 GB');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000195','Pulsa Three paket SMS sesama','Rp152000','Pulsa Three paket SMS sesama');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000196','Pulsa Telkomsel','Rp202000','Pulsa Telkomsel');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000197','Pulsa Smart Fren','Rp7000','Pulsa Smart Fren');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000198','Pulsa Bolt paket SMS sesama','Rp12000','Pulsa Bolt paket SMS sesama bonus kuota 2 GB 24 jam');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000199','Pulsa Mentari','Rp27000','Pulsa Mentari  bonus nelpon 200 menit');
INSERT INTO PRODUK(kode_produk,nama,harga,deskripsi) VALUES ('P0000200','Pulsa Axis kuota 3 GB','Rp52000','Pulsa Axis kuota 3 GB');
