insert into KATEGORI_UTAMA values('K01','Fashion Wanita');
insert into KATEGORI_UTAMA values('K02','Fashion Pria');
insert into KATEGORI_UTAMA values('K03','Fashion Muslim');
insert into KATEGORI_UTAMA values('K04','Fashion Anak');
insert into KATEGORI_UTAMA values('K05','Kecantikan');
insert into KATEGORI_UTAMA values('K06','Kesehatan');
insert into KATEGORI_UTAMA values('K07','Ibu & Bayi');
insert into KATEGORI_UTAMA values('K08','Rumah Tangga');
insert into KATEGORI_UTAMA values('K09','Handphone & Tablet');
insert into KATEGORI_UTAMA values('K10','Laptop & Aksesoris');
insert into KATEGORI_UTAMA values('K11','Komputer & Aksesoris');
insert into KATEGORI_UTAMA values('K12','Elektronik');
insert into KATEGORI_UTAMA values('K13','Kamera, Foto & Video');
insert into KATEGORI_UTAMA values('K14','Otomotif');
insert into KATEGORI_UTAMA values('K15','Olahraga');
insert into KATEGORI_UTAMA values('K16','Film, Musik & Game');
insert into KATEGORI_UTAMA values('K17','Dapur');
insert into KATEGORI_UTAMA values('K18','Office & Stationery');
insert into KATEGORI_UTAMA values('K19','Souvenir, Kado & Hadiah');
insert into KATEGORI_UTAMA values('K20','Mainan & Hobi');
insert into KATEGORI_UTAMA values('K21','Makanan & Minuman');
insert into KATEGORI_UTAMA values('K22','Buku');
insert into KATEGORI_UTAMA values('','');
