INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K01','Fashion Wanita');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K02','Fashion Pria');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K03','Fashion Muslim');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K04','Fashion Anak');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K05','Kecantikan');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K06','Kesehatan');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K07','Ibu & Bayi');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K08','Rumah Tangga');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K09','Handphone & Tablet');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K10','Laptop & Aksesoris');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K11','Komputer & Aksesoris');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K12','Elektronik');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K13','Kamera, Foto & Video');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K14','Otomotif');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K15','Olahraga');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K16','Film, Musik & Game');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K17','Dapur');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K18','Office & Stationery');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K19','Souvenir, Kado & Hadiah');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K20','Mainan & Hobi');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K21','Makanan & Minuman');
INSERT INTO KATEGORI_UTAMA(kode,nama) VALUES ('K22','Buku');
