INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK001','K01','Atasan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK002','K01','Celana');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK003','K01','Dress');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK004','K01','Outerwear');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK005','K01','Setelan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK006','K01','Batik Wanita');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK007','K01','Pakaian Dalam Wanita');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK008','K01','Tas');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK009','K01','Sepatu');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK010','K01','Jam Tangan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK011','K01','Perhiasan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK012','K01','Aksesoris');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK013','K01','Aksesoris Rambut');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK014','K01','Perlengkapan Couple');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK015','K01','Baju Tidur');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK016','K01','Perlengkapan Jahit');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK017','K02','Jam Tangan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK018','K02','Baju Tidur');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK019','K02','Pakaian Dalam Pria');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK020','K02','Outerwear');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK021','K02','Sepatu');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK022','K02','Tas');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK023','K02','Perhiasan Fashion');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK024','K02','Aksesoris');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK025','K02','Celana');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK026','K02','Batik Pria');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK027','K02','Atasan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK028','K03','Outerwear');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK029','K03','Setelan Muslim');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK030','K03','Dress');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK031','K03','Scarf');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK032','K03','Baju Muslim Anak');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK033','K03','Atasan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK034','K03','Aksesoris Jilbab');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK035','K03','Bawahan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK036','K03','Perlengkapan Ibadah');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK037','K04','Perhiasan Anak');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK038','K04','Sepatu Anak Perempuan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK039','K04','Aksesoris Rambut Anak');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK040','K04','Aksesoris Anak');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK041','K04','Tas Anak');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK042','K04','Sepatu Anak Laki-laki');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK043','K04','Pakaian Anak Perempuan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK044','K04','Pakaian Anak Laki-Laki');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK045','K05','Kosmetik');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK046','K05','Perawatan Wajah');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK047','K05','Perawatan Tangan, Kaki dan Kuku');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK048','K05','Perawatan Rambut');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK049','K05','Perawatan Mata');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK050','K05','Styling Rambut');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK051','K05','Peralatan Make Up');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK052','K05','Grooming');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK053','K05','Mandi & Perawatan Tubuh');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK054','K06','Telinga');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK055','K06','Kesehatan Wanita');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK056','K06','Obat & Alat Kesehatan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK057','K06','Health Products');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK058','K06','Kesehatan Gigi & Mulut');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK059','K06','Diet & Vitamin');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK060','K06','Kesehatan Mata');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK061','K06','Perlengkapan Medis');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK062','K06','Kesehatan Lainnya');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK063','K07','Aksesoris Bayi');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK064','K08','Kamar Tidur');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK065','K09','Handphone');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK066','K10','Laptop');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK067','K11','Komputer');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK068','K12','TV');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK069','K13','Kamera');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK070','K14','Aksesoris Mobil');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK071','K15','Basket');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK072','K16','Musik');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK073','K17','Peralatan Dapur');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK074','K18','Alat Tulis');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK075','K19','Boneka');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK076','K20','Figure');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK077','K21','Makanan');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK078','K21','Minuman');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK079','K22','Buku Sekolah');
INSERT INTO SUB_KATEGORI(kode,kode_kategori,nama) VALUES ('SK080','K22','Novel Sastra');
