insert into SUB_KATEGORI values('SK001','K01','Atasan');
insert into SUB_KATEGORI values('SK002','K01','Celana');
insert into SUB_KATEGORI values('SK003','K01','Dress');
insert into SUB_KATEGORI values('SK004','K01','Outerwear');
insert into SUB_KATEGORI values('SK005','K01','Setelan');
insert into SUB_KATEGORI values('SK006','K01','Batik Wanita');
insert into SUB_KATEGORI values('SK007','K01','Pakaian Dalam Wanita');
insert into SUB_KATEGORI values('SK008','K01','Tas');
insert into SUB_KATEGORI values('SK009','K01','Sepatu');
insert into SUB_KATEGORI values('SK010','K01','Jam Tangan');
insert into SUB_KATEGORI values('SK011','K01','Perhiasan');
insert into SUB_KATEGORI values('SK012','K01','Aksesoris');
insert into SUB_KATEGORI values('SK013','K01','Aksesoris Rambut');
insert into SUB_KATEGORI values('SK014','K01','Perlengkapan Couple');
insert into SUB_KATEGORI values('SK015','K01','Baju Tidur');
insert into SUB_KATEGORI values('SK016','K01','Perlengkapan Jahit');
insert into SUB_KATEGORI values('SK017','K02','Jam Tangan');
insert into SUB_KATEGORI values('SK018','K02','Baju Tidur');
insert into SUB_KATEGORI values('SK019','K02','Pakaian Dalam Pria');
insert into SUB_KATEGORI values('SK020','K02','Outerwear');
insert into SUB_KATEGORI values('SK021','K02','Sepatu');
insert into SUB_KATEGORI values('SK022','K02','Tas');
insert into SUB_KATEGORI values('SK023','K02','Perhiasan Fashion');
insert into SUB_KATEGORI values('SK024','K02','Aksesoris');
insert into SUB_KATEGORI values('SK025','K02','Celana');
insert into SUB_KATEGORI values('SK026','K02','Batik Pria');
insert into SUB_KATEGORI values('SK027','K02','Atasan');
insert into SUB_KATEGORI values('SK028','K03','Outerwear');
insert into SUB_KATEGORI values('SK029','K03','Setelan Muslim');
insert into SUB_KATEGORI values('SK030','K03','Dress');
insert into SUB_KATEGORI values('SK031','K03','Scarf');
insert into SUB_KATEGORI values('SK032','K03','Baju Muslim Anak');
insert into SUB_KATEGORI values('SK033','K03','Atasan');
insert into SUB_KATEGORI values('SK034','K03','Aksesoris Jilbab');
insert into SUB_KATEGORI values('SK035','K03','Bawahan');
insert into SUB_KATEGORI values('SK036','K03','Perlengkapan Ibadah');
insert into SUB_KATEGORI values('SK037','K04','Perhiasan Anak');
insert into SUB_KATEGORI values('SK038','K04','Sepatu Anak Perempuan');
insert into SUB_KATEGORI values('SK039','K04','Aksesoris Rambut Anak');
insert into SUB_KATEGORI values('SK040','K04','Aksesoris Anak');
insert into SUB_KATEGORI values('SK041','K04','Tas Anak');
insert into SUB_KATEGORI values('SK042','K04','Sepatu Anak Laki-laki');
insert into SUB_KATEGORI values('SK043','K04','Pakaian Anak Perempuan');
insert into SUB_KATEGORI values('SK044','K04','Pakaian Anak Laki-Laki');
insert into SUB_KATEGORI values('SK045','K05','Kosmetik');
insert into SUB_KATEGORI values('SK046','K05','Perawatan Wajah');
insert into SUB_KATEGORI values('SK047','K05','Perawatan Tangan, Kaki dan Kuku');
insert into SUB_KATEGORI values('SK048','K05','Perawatan Rambut');
insert into SUB_KATEGORI values('SK049','K05','Perawatan Mata');
insert into SUB_KATEGORI values('SK050','K05','Styling Rambut');
