insert into TOKO_JASA_KIRIM values('solution-oriented Electronics','J&T EXPRESS');
insert into TOKO_JASA_KIRIM values('analyzing Computers','PAHALA');
insert into TOKO_JASA_KIRIM values('Future-proofed Toys','WAHANA');
insert into TOKO_JASA_KIRIM values('installation Computers','PAHALA');
insert into TOKO_JASA_KIRIM values('project Tools','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('project Computers','JNE YES');
insert into TOKO_JASA_KIRIM values('reciprocal Health','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('Centralized Home','POS PAKET BIASA');
insert into TOKO_JASA_KIRIM values('monitoring Books','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('functionalities Toys','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('Decentralized Grocery','WAHANA');
insert into TOKO_JASA_KIRIM values('installation Computers','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('Future-proofed Toys','WAHANA');
insert into TOKO_JASA_KIRIM values('time-frame Health','JNE REGULER');
insert into TOKO_JASA_KIRIM values('asynchronous Industrial','WAHANA');
insert into TOKO_JASA_KIRIM values('groupware Books','POS PAKET BIASA');
insert into TOKO_JASA_KIRIM values('non-volatile Games','POS PAKET BIASA');
insert into TOKO_JASA_KIRIM values('Business-focused Jewelery','PAHALA');
insert into TOKO_JASA_KIRIM values('conglomeration Jewelery','JNE OKE');
insert into TOKO_JASA_KIRIM values('alliance Toys','JNE REGULER');
insert into TOKO_JASA_KIRIM values('circuit Automotive','JNE YES');
insert into TOKO_JASA_KIRIM values('analyzer Computers','JNE REGULER');
insert into TOKO_JASA_KIRIM values('mission-critical Electronics','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('Robust Garden','WAHANA');
insert into TOKO_JASA_KIRIM values('Up-sized Movies','PAHALA');
insert into TOKO_JASA_KIRIM values('Future-proofed Toys','JNE REGULER');
insert into TOKO_JASA_KIRIM values('Implemented Grocery','JNE REGULER');
insert into TOKO_JASA_KIRIM values('knowledge base Games','WAHANA');
insert into TOKO_JASA_KIRIM values('customer loyalty Movies','POS PAKET BIASA');
insert into TOKO_JASA_KIRIM values('monitoring Books','JNE REGULER');
insert into TOKO_JASA_KIRIM values('global Tools','J&T EXPRESS');
insert into TOKO_JASA_KIRIM values('Ameliorated Movies','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('Compatible Outdoors','WAHANA');
insert into TOKO_JASA_KIRIM values('Advanced Baby','LION PARCEL');
insert into TOKO_JASA_KIRIM values('algorithm Garden','POS PAKET BIASA');
insert into TOKO_JASA_KIRIM values('eco-centric Industrial','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('Implemented Grocery','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('complexity Tools','WAHANA');
insert into TOKO_JASA_KIRIM values('Persevering Outdoors','WAHANA');
insert into TOKO_JASA_KIRIM values('groupware Books','LION PARCEL');
insert into TOKO_JASA_KIRIM values('solution-oriented Baby','JNE REGULER');
insert into TOKO_JASA_KIRIM values('Persevering Outdoors','LION PARCEL');
insert into TOKO_JASA_KIRIM values('Customizable Shoes','WAHANA');
insert into TOKO_JASA_KIRIM values('Diverse Movies','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('algorithm Music','JNE REGULER');
insert into TOKO_JASA_KIRIM values('task-force Movies','TIKI REGULER');
insert into TOKO_JASA_KIRIM values('system engine Computers','JNE REGULER');
insert into TOKO_JASA_KIRIM values('Implemented Games','J&T EXPRESS');
insert into TOKO_JASA_KIRIM values('circuit Automotive','POS PAKET KILAT');
insert into TOKO_JASA_KIRIM values('Stand-alone Outdoors','PAHALA');
