INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('solution-oriented Electronics','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzing Computers','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Future-proofed Toys','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('installation Computers','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('project Tools','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('project Computers','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('reciprocal Health','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Centralized Home','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('monitoring Books','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('functionalities Toys','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Decentralized Grocery','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('installation Computers','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Future-proofed Toys','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('time-frame Health','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('asynchronous Industrial','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('groupware Books','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('non-volatile Games','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Business-focused Jewelery','JNE OKE');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('conglomeration Jewelery','JNE OKE');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('alliance Toys','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('circuit Automotive','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzer Computers','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('mission-critical Electronics','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Robust Garden','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Up-sized Movies','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Future-proofed Toys','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Implemented Grocery','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('knowledge base Games','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('customer loyalty Movies','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('monitoring Books','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('global Tools','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Ameliorated Movies','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Compatible Outdoors','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Advanced Baby','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('algorithm Garden','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('eco-centric Industrial','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Implemented Grocery','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('complexity Tools','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Persevering Outdoors','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('groupware Books','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('solution-oriented Baby','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Persevering Outdoors','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Customizable Shoes','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Diverse Movies','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('algorithm Music','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('task-force Movies','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('system engine Computers','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Implemented Games','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('circuit Automotive','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Stand-alone Outdoors','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('software Garden','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('software Garden','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Implemented Games','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('tertiary Home','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzing Computers','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('software Books','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('asymmetric Baby','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('empowering Beauty','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzing Computers','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('asynchronous Industrial','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Customer-focused Kids','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Re-engineered Jewelery','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Secured Baby','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Implemented Games','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Stand-alone Music','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('mission-critical Electronics','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Compatible Outdoors','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('asynchronous Industrial','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzing Computers','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('grid-enabled Music','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Re-contextualized Automotive','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Face to face Electronics','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('holistic Shoes','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('functionalities Toys','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('knowledge base Games','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('algorithm Industrial','JNE OKE');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('monitoring Books','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('analyzer Computers','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Compatible Outdoors','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('installation Computers','WAHANA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('empowering Beauty','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('holistic Shoes','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('mission-critical Baby','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('grid-enabled Music','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('solution-oriented Baby','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Re-engineered Jewelery','JNE OKE');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Business-focused Jewelery','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Quality-focused Music','JNE REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Face to face Electronics','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Stand-alone Music','POS PAKET BIASA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('groupware Books','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('radical Movies','PAHALA');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('instruction set Beauty','LION PARCEL');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('installation Computers','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('frame Beauty','JNE YES');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('Organic Electronics','TIKI REGULER');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('reciprocal Health','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('functionalities Home','POS PAKET KILAT');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('approach Kids','J&T EXPRESS');
INSERT INTO TOKO_JASA_KIRIM(nama_toko,jasa_kirim) VALUES ('non-volatile Games','J&T EXPRESS');
